/**
 * The owner's own words, taken out of the project's sessions by rule (Spec §3.3 "原话整理", §1.3; CKC-05 AC-13's
 * input): only what the owner typed — never a tool result, a block the host or system injected, a command wrapper, a
 * compaction summary, a subagent's side branch, or the environment and instruction files Codex injects. Messages keep
 * their words as typed; text pasted into them is marked, not cut. Each utterance names the session source it can be
 * cited by, and the totals say how much there is (D37).
 *
 * The sessions are invented Claude Code and Codex logs of an invented project, "Ledger", written in the shapes those
 * hosts write: typed prompts, prompts queued while the agent worked, tool results, reminders, commands, a compaction,
 * a subagent, a headless run.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const fakeHome = mkdtempSync(join(tmpdir(), 'pk-words-home-'));
process.env.USERPROFILE = fakeHome;
process.env.HOME = fakeHome;

const { ProjectStore } = await import('../../store/project-store.ts');
const { keeperTools } = await import('../../keeper/tools.ts');
const { sessionSources } = await import('./read.ts');
type Project = import('../../model/types.ts').Project;
type Source = import('../../model/types.ts').Source;
type LocatedSession = import('./locate.ts').LocatedSession;

const CWD = 'D:\\ledger';
const t = (minute: number) => new Date(Date.UTC(2026, 8, 10, 1, minute)).toISOString();

// ───────────────────────── Claude Code ─────────────────────────

const REPORT = "Here is the reviewer's report:\n\n# Review of export\n\n- Finding 1: totals are rounded twice.\n- Finding 2: the header row is missing.\n\n| Item | Status |\n|---|---|\n| CSV | ok |\n| PDF | missing |\n\nWhat do you think?";
const CODE = 'This fails:\n\n```\nTypeError: total is undefined\n```\n\nPlease look.';

function claudeLog(sessionId: string, entrypoint: string, records: Record<string, unknown>[]): string {
  return records.map((r, i) => JSON.stringify({ sessionId, cwd: CWD, isSidechain: false, userType: 'external', entrypoint, uuid: `${sessionId}-${i}`, version: '2.1.0', ...r })).join('\n');
}
const human = (minute: number, content: unknown, extra: Record<string, unknown> = {}) => ({ type: 'user', timestamp: t(minute), origin: { kind: 'human' }, promptSource: 'sdk', message: { role: 'user', content }, ...extra });
const said = (minute: number, text: string, extra: Record<string, unknown> = {}) => ({ type: 'assistant', timestamp: t(minute), message: { role: 'assistant', model: 'claude-test', content: [{ type: 'text', text }] }, ...extra });

const CLAUDE_MAIN = claudeLog('c1a0e5f1-0000-4000-8000-000000000001', 'claude-desktop', [
  human(0, 'Invoices must never be deleted, only voided.'),
  { type: 'assistant', timestamp: t(1), message: { role: 'assistant', model: 'claude-test', content: [{ type: 'text', text: 'Understood; I will read the plan.' }, { type: 'tool_use', id: 'tu1', name: 'Read', input: { file_path: 'D:\\ledger\\docs\\PLAN.md' } }] } },
  { type: 'user', timestamp: t(2), message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'tu1', content: '# Plan\nsecret=abcdefghijklmnop\nExport invoices as CSV.' }] }, toolUseResult: { type: 'text' } },
  human(3, '<system-reminder>\nThe date is 2026-09-10.\n</system-reminder>\nKeep the export under two seconds.'),
  { type: 'user', timestamp: t(4), isMeta: true, message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>' } },
  { type: 'user', timestamp: t(5), message: { role: 'user', content: '<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>' } },
  { type: 'user', timestamp: t(6), message: { role: 'user', content: '<local-command-stdout>Set model to opus</local-command-stdout>' } },
  { type: 'user', timestamp: t(7), origin: { kind: 'task-notification' }, promptSource: 'sdk', message: { role: 'user', content: '<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n<summary>Background task finished</summary>\n</task-notification>' } },
  { type: 'system', subtype: 'compact_boundary', timestamp: t(8), content: 'Conversation compacted' },
  { type: 'user', timestamp: t(9), isCompactSummary: true, isVisibleInTranscriptOnly: true, message: { role: 'user', content: 'This session is being continued from a previous conversation that ran out of context. The conversation is summarized below:\nThe owner wants invoices voided, never deleted.' } },
  { type: 'user', timestamp: t(10), isSidechain: true, message: { role: 'user', content: 'Read docs/PLAN.md and report the export rules.' } },
  said(11, 'The plan says CSV.', { isSidechain: true }),
  { type: 'attachment', timestamp: t(12), attachment: { type: 'queued_command', prompt: 'Also, PDFs need a footer with the page number.', commandMode: 'prompt', origin: { kind: 'human' }, timestamp: t(12) } },
  { type: 'attachment', timestamp: t(13), attachment: { type: 'queued_command', prompt: '<task-notification>\n<task-id>b2</task-id>\n<summary>Build finished</summary>\n</task-notification>', commandMode: 'task-notification', timestamp: t(13) } },
  { type: 'user', timestamp: t(14), message: { role: 'user', content: [{ type: 'text', text: '[Request interrupted by user]' }] } },
  human(15, REPORT),
  human(16, CODE),
  human(17, [{ type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'iVBORw0KGgo=' } }, { type: 'text', text: 'The button in this screenshot is too small.' }]),
  human(18, 'My test key is sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123 and it must not be committed.'),
  said(19, 'Noted.'),
]);
const CLAUDE_HEADLESS = claudeLog('c1a0e5f1-0000-4000-8000-000000000002', 'sdk-cli', [
  { type: 'user', timestamp: t(20), message: { role: 'user', content: 'Review the export module and list defects.' } },
  said(21, 'Two defects.'),
]);

// ───────────────────────── Codex ─────────────────────────

const codexLine = (minute: number, type: string, payload: Record<string, unknown>) => JSON.stringify({ timestamp: t(minute), type, payload });
const codexUser = (minute: number, parts: Record<string, unknown>[]) => codexLine(minute, 'response_item', { type: 'message', role: 'user', content: parts });
const text = (s: string) => ({ type: 'input_text', text: s });

const CODEX_MAIN = [
  codexLine(30, 'session_meta', { id: '019a0000-0000-7000-8000-000000000003', cwd: CWD, originator: 'codex-tui', source: 'cli', thread_source: 'user', cli_version: '0.99.0' }),
  codexUser(30, [text('# AGENTS.md instructions for D:\\ledger\n\n<INSTRUCTIONS>\nFollow the house rules.\n</INSTRUCTIONS>')]),
  codexUser(30, [text('<environment_context>\n  <cwd>D:\\ledger</cwd>\n  <shell>powershell</shell>\n</environment_context>')]),
  codexLine(30, 'response_item', { type: 'message', role: 'developer', content: [text('<collaboration_mode>default</collaboration_mode>')] }),
  codexLine(31, 'turn_context', { cwd: CWD, model: 'gpt-test' }),
  codexUser(31, [text('<recommended_plugins>\n- docs\n</recommended_plugins>'), text('Voided invoices stay visible to the accountant.')]),
  codexLine(31, 'event_msg', { type: 'item_completed', item: { type: 'UserMessage', id: 'um1', content: [{ type: 'text', text: 'Voided invoices stay visible to the accountant.' }] } }),
  codexUser(32, [text('<in-app-browser-context>\nurl: http://localhost:5173\n</in-app-browser-context>')]),
  codexLine(33, 'response_item', { type: 'function_call', name: 'shell', arguments: '{"command":["rg","void"]}', call_id: 'c1' }),
  codexLine(33, 'response_item', { type: 'function_call_output', call_id: 'c1', output: 'src/void.ts: export function voidInvoice()' }),
  codexLine(34, 'response_item', { type: 'message', role: 'assistant', content: [{ type: 'output_text', text: 'Voided invoices are kept.' }] }),
  codexLine(35, 'compacted', { message: 'The owner wants voided invoices kept.', replacement_history: [] }),
  codexUser(35, [text('Another language model started to solve this problem and produced a summary of its thinking process. Here is the summary: the owner wants voided invoices kept.')]),
  codexUser(36, [text('<image name=[Image #1]>'), { type: 'input_image', image_url: 'data:image/png;base64,iVBORw0KGgo=' }, text('</image>'), text('The void button in this screenshot is too small.')]),
  codexLine(37, 'response_item', { type: 'message', role: 'assistant', content: [{ type: 'output_text', text: 'I will enlarge it.' }] }),
].join('\n');
const CODEX_SUBAGENT = [
  codexLine(40, 'session_meta', { id: '019a0000-0000-7000-8000-000000000004', cwd: CWD, originator: 'Codex Desktop', source: { subagent: { thread_spawn: { parent_thread_id: '019a0000-0000-7000-8000-000000000003' } } }, thread_source: 'subagent', agent_role: 'reviewer' }),
  codexUser(40, [text('Review the void module and report.')]),
  codexLine(41, 'response_item', { type: 'message', role: 'assistant', content: [{ type: 'output_text', text: 'Reviewed.' }] }),
].join('\n');
const CODEX_EXEC = [
  codexLine(45, 'session_meta', { id: '019a0000-0000-7000-8000-000000000005', cwd: CWD, originator: 'codex_exec', source: 'exec', thread_source: 'user' }),
  codexUser(45, [text('Audit the export code for rounding errors.')]),
  codexLine(46, 'response_item', { type: 'message', role: 'assistant', content: [{ type: 'output_text', text: 'One rounding error.' }] }),
].join('\n');

// ───────────────────────── the project's session sources ─────────────────────────

function located(host: 'claude' | 'codex', file: string, sessionId: string, isSubagent = false): LocatedSession {
  const st = statSync(file);
  return { host, file, cwd: CWD, sessionId, bytes: st.size, mtimeMs: st.mtimeMs, isSubagent, home: fakeHome };
}

function setUp() {
  const dir = mkdtempSync(join(tmpdir(), 'pk-words-logs-'));
  mkdirSync(join(dir, 'claude'), { recursive: true });
  mkdirSync(join(dir, 'codex'), { recursive: true });
  const files = {
    claudeMain: join(dir, 'claude', 'c1a0e5f1-0000-4000-8000-000000000001.jsonl'),
    claudeHeadless: join(dir, 'claude', 'c1a0e5f1-0000-4000-8000-000000000002.jsonl'),
    codexMain: join(dir, 'codex', 'rollout-2026-09-10T01-30-00-019a0000-0000-7000-8000-000000000003.jsonl'),
    codexSub: join(dir, 'codex', 'rollout-2026-09-10T01-40-00-019a0000-0000-7000-8000-000000000004.jsonl'),
    codexExec: join(dir, 'codex', 'rollout-2026-09-10T01-45-00-019a0000-0000-7000-8000-000000000005.jsonl'),
  };
  writeFileSync(files.claudeMain, CLAUDE_MAIN);
  writeFileSync(files.claudeHeadless, CLAUDE_HEADLESS);
  writeFileSync(files.codexMain, CODEX_MAIN);
  writeFileSync(files.codexSub, CODEX_SUBAGENT);
  writeFileSync(files.codexExec, CODEX_EXEC);
  const store = ProjectStore.open('p1', mkdtempSync(join(tmpdir(), 'pk-words-store-')));
  const put = (l: LocatedSession) => { const { sources } = sessionSources('p1', l, 'scope_sessions'); store.sources.putMany(sources); return sources; };
  const claudeMain = put(located('claude', files.claudeMain, 'c1a0e5f1-0000-4000-8000-000000000001'));
  put(located('claude', files.claudeHeadless, 'c1a0e5f1-0000-4000-8000-000000000002'));
  put(located('codex', files.codexMain, '019a0000-0000-7000-8000-000000000003'));
  put(located('codex', files.codexSub, '019a0000-0000-7000-8000-000000000004', true));
  put(located('codex', files.codexExec, '019a0000-0000-7000-8000-000000000005'));
  // The owner's messages in the Keeper conversation are owner statements too (Spec §1.2); an agent's query is not.
  const pi = (id: string, who: 'owner' | 'agent', minute: number, body: string) => store.sources.put({ id, projectId: 'p1', title: `Keeper conversation · message ${minute}`, anchor: { kind: 'session', host: 'pi', sessionId: 'conv_1', file: '', cwd: CWD, messageStart: minute, messageEnd: minute, at: t(minute) }, ids: [], version: { fingerprint: id, readAt: t(minute), commit: null }, excerpt: `[${who} ${t(minute)}]\n${body}`, usedAs: null, usedAsBy: null, availability: null, movedTo: null, scopeItemId: 'scope_main', hasCredential: false, bytes: body.length } as Source);
  pi('src_pi_owner', 'owner', 50, 'Please treat the old sync design as dropped.');
  pi('src_pi_agent', 'agent', 51, 'Which task should I take next?');
  const project = { id: 'p1', name: 'Ledger', language: 'en', locations: [CWD], scope: [], scopeQuestions: [], keeperFiles: [], roles: [], organizingPaused: false, createdAt: t(0), lastOpenedAt: null, lastScopedAt: null } as unknown as Project;
  const tools = keeperTools({ store, project, jobId: 'job_frame', jobKind: 'Organizing', model: null });
  const call = async (args: Record<string, unknown>) => {
    const tool = tools.find((x) => x.name === 'pk_owner_utterances');
    assert.ok(tool, 'no tool pk_owner_utterances: the framing round cannot take out the owner’s own words');
    const run = tool.execute as unknown as (id: string, p: unknown) => Promise<{ content: { text: string }[]; isError?: boolean }>;
    const r = await run('call', args);
    const body = r.content.map((c) => c.text).join('\n');
    assert.notEqual(r.isError, true, body);
    return JSON.parse(body) as { utterances: Utterance[]; next: string | null; total: number; totalChars: number };
  };
  return { store, call, claudeMain };
}

interface Utterance { sourceId: string; host: string; at: string; text: string; chars: number; pasted?: { start: number; end: number; clue: string }[]; headless?: boolean }

const OWNER_WORDS = [
  'Invoices must never be deleted, only voided.',
  'Keep the export under two seconds.',
  'Also, PDFs need a footer with the page number.',
  REPORT,
  CODE,
  'The button in this screenshot is too small.',
  'My test key is [credential redacted] and it must not be committed.',
  'Review the export module and list defects.',
  'Voided invoices stay visible to the accountant.',
  'The void button in this screenshot is too small.',
  'Audit the export code for rounding errors.',
  'Please treat the old sync design as dropped.',
];
const NOT_THE_OWNER = [
  'Understood; I will read the plan', 'secret=', 'The date is 2026-09-10', 'Caveat:', '/model', 'Set model to opus', 'task-notification',
  'Background task finished', 'Build finished', 'This session is being continued', 'Read docs/PLAN.md and report', '[Request interrupted',
  'house rules', 'environment_context', '<cwd>', 'recommended_plugins', 'in-app-browser-context', 'Another language model', '<image',
  'Review the void module', 'Which task should I take next', 'The plan says CSV',
];

async function everything(call: Awaited<ReturnType<typeof setUp>>['call'], args: Record<string, unknown> = {}) {
  const out: Utterance[] = [];
  let cursor: string | null = null;
  for (let page = 0; page < 50; page++) {
    const r = await call({ ...args, ...(cursor ? { cursor } : {}) });
    out.push(...r.utterances);
    cursor = r.next;
    if (!cursor) return { out, total: r.total, totalChars: r.totalChars };
  }
  throw new Error('the cursor never ended');
}

test('only what the owner typed comes out, word for word, in time order, each with the source it can be cited by (Spec §3.3; CKC-05 AC-13)', async () => {
  const { store, call } = setUp();
  const r = await call({ limit: 100 });
  assert.deepEqual(r.utterances.map((u) => u.text), OWNER_WORDS, 'every owner message and nothing else, as typed');
  for (const u of r.utterances) for (const bad of NOT_THE_OWNER) assert.ok(!u.text.includes(bad), `“${bad}” is not the owner’s: ${u.text}`);
  assert.equal(r.total, OWNER_WORDS.length);
  assert.equal(r.totalChars, OWNER_WORDS.reduce((n, w) => n + [...w].length, 0), 'the total says how much there is to read (D37)');
  assert.equal(r.next, null);
  for (const u of r.utterances) {
    assert.equal(u.chars, [...u.text].length);
    const source = store.sources.get(u.sourceId);
    assert.ok(source && source.anchor.kind === 'session', `${u.text.slice(0, 30)} names a session source`);
    const squash = (s: string) => s.replace(/\s+/g, ' ');
    assert.ok(squash(source.excerpt).includes(squash(u.text)), `the words can be opened in the source they cite: ${u.text.slice(0, 40)}`);
    assert.ok(!Number.isNaN(Date.parse(u.at)));
  }
  assert.deepEqual([...new Set(r.utterances.map((u) => u.host))].sort(), ['claude', 'codex', 'pi']);
  const at = r.utterances.map((u) => u.at);
  assert.deepEqual(at, [...at].sort(), 'oldest first: a later word replaces an earlier one (§1.3)');
});

test('a headless run is marked, not dropped: its prompt may not be the owner’s (Spec §3.3)', async () => {
  const { call } = setUp();
  const r = await call({ limit: 100 });
  const headless = r.utterances.filter((u) => u.headless === true).map((u) => u.text).sort();
  assert.deepEqual(headless, ['Audit the export code for rounding errors.', 'Review the export module and list defects.']);
});

test('text pasted into an owner’s message is marked where it is recognisable; the message itself stays whole (Spec §3.3)', async () => {
  const { call } = setUp();
  const r = await call({ limit: 100 });
  const report = r.utterances.find((u) => u.text === REPORT)!;
  assert.ok(report.pasted && report.pasted.length > 0, 'the pasted report is marked');
  const pieces = report.pasted.map((p) => report.text.slice(p.start, p.end));
  assert.ok(pieces.some((s) => s.startsWith('# Review of export') && s.includes('| PDF | missing |')), pieces.join(' || '));
  assert.ok(pieces.every((s) => !s.includes("Here is the reviewer's report") && !s.includes('What do you think?')), 'the owner’s own lines around it are not inside a mark');
  const code = r.utterances.find((u) => u.text === CODE)!;
  assert.ok(code.pasted?.some((p) => /code/i.test(p.clue) && code.text.slice(p.start, p.end).includes('TypeError')), 'a pasted code block is marked');
  const plain = r.utterances.find((u) => u.text === 'Invoices must never be deleted, only voided.')!;
  assert.ok(!plain.pasted || plain.pasted.length === 0, 'a plain message has no mark');
});

test('pages follow the cursor to the end; the time and the session filters narrow the set and its totals (Spec §3.3)', async () => {
  const { call, claudeMain } = setUp();
  const paged = await everything(call, { limit: 5 });
  assert.deepEqual(paged.out.map((u) => u.text), OWNER_WORDS, 'the pages together are the whole list, once each');
  assert.equal(paged.total, OWNER_WORDS.length);

  const since = await everything(call, { since: t(15) });
  assert.deepEqual(since.out.map((u) => u.text), OWNER_WORDS.slice(3), 'from that time on');
  assert.equal(since.total, OWNER_WORDS.length - 3);

  const session = await everything(call, { sessionSourceId: claudeMain[0]!.id });
  assert.deepEqual(session.out.map((u) => u.text), OWNER_WORDS.slice(0, 7), 'one session, named by any of its sources');
  assert.equal(session.totalChars, OWNER_WORDS.slice(0, 7).reduce((n, w) => n + [...w].length, 0));
});

test('a session’s transcript shows as the owner only what the owner typed (Spec §1.2, §3.3)', () => {
  const { claudeMain } = setUp();
  const transcript = claudeMain.map((s) => s.excerpt).join('\n\n');
  const blocks = transcript.split(/\n\n(?=\[\d+\] )/).filter((b) => /^\[\d+\] OWNER\b/.test(b));
  const owner = blocks.join('\n');
  assert.ok(owner.includes('Also, PDFs need a footer'), 'a prompt queued while the agent worked is the owner’s');
  for (const bad of ['This session is being continued', 'Read docs/PLAN.md and report', 'Caveat:', '[Request interrupted']) {
    assert.ok(!owner.includes(bad), `“${bad}” is not shown as the owner’s words`);
  }
});

/**
 * Who said a Keeper conversation message, and when, are recorded on its source when the message is stored (batch D4;
 * Spec §1.2, §3.3). They used to be read back out of the heading the excerpt shows the message under, "[owner <time>]":
 * that heading is a display format of our own, and had it changed, the owner's words would have dropped out of
 * pk_owner_utterances without a sign. A message stored before the record existed is still read from its heading.
 */
test('the owner’s words in the Keeper conversation are found by what the source records, whatever heading the excerpt shows', async () => {
  const store = ProjectStore.open('p1', mkdtempSync(join(tmpdir(), 'pk-words-said-')));
  const message = (id: string, minute: number, heading: string, body: string, said?: { by: 'owner' | 'agent'; wordsFrom: number }) => store.sources.put({
    id, projectId: 'p1', title: `Keeper conversation · message ${minute}`,
    anchor: { kind: 'session', host: 'pi', sessionId: 'conv_2', file: '', cwd: CWD, messageStart: minute, messageEnd: minute, at: t(minute) },
    ids: [], version: { fingerprint: id, readAt: t(minute), commit: null }, excerpt: `${heading}${body}`, usedAs: null, usedAsBy: null,
    availability: null, movedTo: null, scopeItemId: 'scope_main', hasCredential: false, bytes: body.length, ...(said ? { said } : {}),
  } as Source);
  // Messages stored with the record, their excerpts headed in some other way than today's.
  const ownerHeading = `Owner, ${t(60)}:\n`;
  message('src_said_owner', 60, ownerHeading, 'Voided invoices keep their number.', { by: 'owner', wordsFrom: ownerHeading.length });
  const agentHeading = `Agent query, ${t(61)}:\n`;
  message('src_said_agent', 61, agentHeading, 'Which invoice should I void first?', { by: 'agent', wordsFrom: agentHeading.length });
  // What the record says decides, not the heading: an agent's query headed the way the owner's messages once were.
  const lookalike = `[owner ${t(62)}]\n`;
  message('src_said_lookalike', 62, lookalike, 'Quoting the owner: void, never delete.', { by: 'agent', wordsFrom: lookalike.length });
  // A message stored before the record existed is read from its heading, as before.
  message('src_before_record', 63, `[owner ${t(63)}]\n`, 'Credit notes come later.');

  const project = { id: 'p1', name: 'Ledger', language: 'en', locations: [CWD], scope: [], scopeQuestions: [], keeperFiles: [], roles: [], organizingPaused: false, createdAt: t(0), lastOpenedAt: null, lastScopedAt: null } as unknown as Project;
  const tool = keeperTools({ store, project, jobId: 'job_frame', jobKind: 'Organizing', model: null }).find((x) => x.name === 'pk_owner_utterances')!;
  const run = tool.execute as unknown as (id: string, p: unknown) => Promise<{ content: { text: string }[]; isError?: boolean }>;
  const r = await run('call', { limit: 100 });
  const body = r.content.map((c) => c.text).join('\n');
  assert.notEqual(r.isError, true, body);
  const found = (JSON.parse(body) as { utterances: Utterance[] }).utterances;
  assert.deepEqual(found.map((u) => [u.sourceId, u.text, u.at]), [
    ['src_said_owner', 'Voided invoices keep their number.', t(60)],
    ['src_before_record', 'Credit notes come later.', t(63)],
  ], 'the owner’s words, whole and without the heading, at the time they were said; no agent’s query');
});
